# Generated by Django 3.1 on 2020-08-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='f_name',
        ),
        migrations.AddField(
            model_name='contact',
            name='l_name',
            field=models.CharField(default='kipkemoi', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='testing', max_length=100),
            preserve_default=False,
        ),
    ]
