# Generated by Django 3.1 on 2020-08-21 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffice', '0002_auto_20200821_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='l_name',
            new_name='last_name',
        ),
    ]
